from . import CATEGORY
from ...utils.constants import BLUE_CHANNEL_ID, FUNCTION, GREEN_CHANNEL_ID, Input, INTENSITY_ID, RED_CHANNEL_ID
from ...utils.helpers.comfy import safe_send_sync
from ...utils.helpers.logic import normalize_json_input

# region LF_LUTGeneration
class LF_LUTGeneration:
    @classmethod
    def INPUT_TYPES(self):
        return {
            "required": {
                "color_analysis_dataset": (Input.JSON, {
                    "tooltip": "Transformation dataset generated by Color Analysis Node."
                }),
            },
            "optional": {
                "ui_widget": (Input.LF_TAB_BAR_CHART, {
                    "default": {}
                })
            },
            "hidden": {
                "node_id": "UNIQUE_ID"
            }
        }

    CATEGORY = CATEGORY
    FUNCTION = FUNCTION
    OUTPUT_IS_LIST = (False,)
    OUTPUT_NODE = True
    OUTPUT_TOOLTIPS = (
        "LUT dataset for the image.",
    )
    RETURN_NAMES = ("lut_dataset",)
    RETURN_TYPES = (Input.JSON,)

    def on_exec(self, **kwargs: dict):
        color_analysis: dict = normalize_json_input(kwargs.get("color_analysis_dataset"))

        lut_datasets: dict = {}
        for image_key, color_analysis in color_analysis.items():
            nodes: list[dict] = []
            dataset: dict = {
                "columns": [
                    {"id": INTENSITY_ID, "title": "Color Intensity"},
                    {"id": RED_CHANNEL_ID, "title": "Red Channel LUT"},
                    {"id": GREEN_CHANNEL_ID, "title": "Green Channel LUT"},
                    {"id": BLUE_CHANNEL_ID, "title": "Blue Channel LUT"}
                ],
                "nodes": nodes
            }

            for node in color_analysis["nodes"]:
                i = node["cells"][INTENSITY_ID]["value"]
                r = node["cells"][RED_CHANNEL_ID]["value"]
                g = node["cells"][GREEN_CHANNEL_ID]["value"]
                b = node["cells"][BLUE_CHANNEL_ID]["value"]

                lut_node = {
                    "id": INTENSITY_ID,
                    "cells": {
                        INTENSITY_ID: {"value": i},
                        RED_CHANNEL_ID: {"value": r, "shape": "number"},
                        GREEN_CHANNEL_ID: {"value": g, "shape": "number"},
                        BLUE_CHANNEL_ID: {"value": b, "shape": "number"}
                    }
                }
                nodes.append(lut_node)

            lut_datasets[image_key] = dataset

        safe_send_sync("lutgeneration", {
            "datasets": lut_datasets
        }, kwargs.get("node_id"))

        return (lut_datasets,)
# endregion

# region Mappings
NODE_CLASS_MAPPINGS = {
    "LF_LUTGeneration": LF_LUTGeneration,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LF_LUTGeneration": "LUT Generation",
}
# endregion
